apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginxdata
spec:
  storageClassName: ionos-enterprise-hdd
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteOnce
